import { lazy, type ComponentType, type LazyExoticComponent } from 'react'
import {
  Braces,
  CodeXml,
  Binary,
  Fingerprint,
  KeyRound,
  Link,
  Clock3,
  Hash,
  Regex,
  LockKeyhole,
  Palette,
  AlignLeft,
  GitCompareArrows,
  FileJson2,
  FileText,
  CalendarClock,
  QrCode,
  CaseSensitive,
  Calculator,
  Contrast,
  ScanLine,
  Image,
  FileStack,
  Scaling,
  RotateCw,
  FileSearch,
  Minimize2,
  Scissors,
  ListOrdered,
  Crop,
  FileSpreadsheet,
  ArrowLeftRight,
  WandSparkles,
  Wrench,
  Globe,
  BookOpen,
  type LucideIcon,
} from 'lucide-react'

export const categories = [
  'Encoders',
  'Generators',
  'Developer',
  'Converters',
  'Utilities',
  'Image',
  'PDF',
  'Text',
  'Web',
  'Resources',
] as const
export type ToolCategory = (typeof categories)[number]
export const categoryIcons: Record<ToolCategory, LucideIcon> = {
  Encoders: Braces,
  Generators: WandSparkles,
  Developer: CodeXml,
  Converters: ArrowLeftRight,
  Utilities: Wrench,
  Image,
  PDF: FileStack,
  Text: AlignLeft,
  Web: Globe,
  Resources: BookOpen,
}
export interface ToolDefinition {
  id: string
  name: string
  description: string
  category: ToolCategory
  path: string
  icon: LucideIcon
  keywords: string[]
  color: string
  component: LazyExoticComponent<ComponentType>
  acceptsFileTypes?: readonly string[]
  producesFileTypes?: readonly string[]
  workspaceCompatible?: boolean
  experimental?: boolean
}

const definitions = [
  {
    id: 'json',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify your JSON with ease.',
    category: 'Developer',
    icon: Braces,
    keywords: ['beautify', 'validator', 'pretty', 'object'],
    color: 'amber',
    component: lazy(() => import('../tools/json/JsonTool')),
  },
  {
    id: 'base64',
    name: 'Base64 Encoder / Decoder',
    description: 'Encode and decode text in Base64 format.',
    category: 'Encoders',
    icon: Binary,
    keywords: ['unicode', 'encode', 'decode'],
    color: 'blue',
    component: lazy(() => import('../tools/base64/Base64Tool')),
  },
  {
    id: 'uuid',
    name: 'UUID Generator',
    description: 'Generate unique, cryptographically secure UUIDs.',
    category: 'Generators',
    icon: Fingerprint,
    keywords: ['guid', 'random', 'identifier', 'v4'],
    color: 'purple',
    component: lazy(() => import('../tools/uuid/UuidTool')),
  },
  {
    id: 'jwt',
    name: 'JWT Decoder',
    description: 'Inspect the header and payload of a JWT token.',
    category: 'Developer',
    icon: KeyRound,
    keywords: ['token', 'claims', 'authentication'],
    color: 'rose',
    component: lazy(() => import('../tools/jwt/JwtTool')),
  },
  {
    id: 'regex',
    name: 'Regex Tester',
    description: 'Test patterns and explore matches in real time.',
    category: 'Developer',
    icon: Regex,
    keywords: ['regular expression', 'pattern', 'match'],
    color: 'teal',
    component: lazy(() => import('../tools/regex/RegexTool')),
  },
  {
    id: 'password',
    name: 'Password Generator',
    description: 'Create strong, secure passwords in a click.',
    category: 'Generators',
    icon: LockKeyhole,
    keywords: ['random', 'secure', 'credentials'],
    color: 'green',
    component: lazy(() => import('../tools/password/PasswordTool')),
  },
  {
    id: 'url',
    name: 'URL Encoder / Decoder',
    description: 'Encode or decode URLs and query components.',
    category: 'Encoders',
    icon: Link,
    keywords: ['uri', 'percent', 'encode', 'decode'],
    color: 'blue',
    component: lazy(() => import('../tools/url/UrlTool')),
  },
  {
    id: 'timestamp',
    name: 'Unix Timestamp Converter',
    description: 'Convert timestamps into readable dates and back.',
    category: 'Converters',
    icon: Clock3,
    keywords: ['epoch', 'time', 'date', 'seconds', 'milliseconds'],
    color: 'amber',
    component: lazy(() => import('../tools/timestamp/TimestampTool')),
  },
  {
    id: 'hash',
    name: 'Hash Generator',
    description: 'Generate SHA hashes using native Web Crypto.',
    category: 'Generators',
    icon: Hash,
    keywords: ['sha1', 'sha256', 'sha384', 'sha512', 'digest'],
    color: 'purple',
    component: lazy(() => import('../tools/hash/HashTool')),
  },
  {
    id: 'color',
    name: 'Color Converter',
    description: 'Move effortlessly between HEX, RGB, and HSL.',
    category: 'Converters',
    icon: Palette,
    keywords: ['hex', 'rgb', 'hsl', 'picker'],
    color: 'rose',
    component: lazy(() => import('../tools/color/ColorTool')),
  },
  {
    id: 'lorem',
    name: 'Lorem Ipsum Generator',
    description: 'Create placeholder text for your next project.',
    category: 'Utilities',
    icon: AlignLeft,
    keywords: ['placeholder', 'paragraph', 'sentence', 'words'],
    color: 'teal',
    component: lazy(() => import('../tools/lorem/LoremTool')),
  },
  {
    id: 'diff',
    name: 'Text Diff Checker',
    description: 'Compare texts and see exactly what changed.',
    category: 'Utilities',
    icon: GitCompareArrows,
    keywords: ['compare', 'difference', 'lines', 'merge'],
    color: 'green',
    component: lazy(() => import('../tools/diff/DiffTool')),
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML Converter',
    description: 'Convert structured data between JSON and YAML.',
    category: 'Converters',
    icon: FileJson2,
    keywords: ['yaml', 'yml', 'json', 'serialize'],
    color: 'amber',
    component: lazy(() => import('../tools/json-yaml/JsonYamlTool')),
  },
  {
    id: 'markdown',
    name: 'Markdown Previewer',
    description: 'Write Markdown with a live GitHub-style preview.',
    category: 'Developer',
    icon: FileText,
    keywords: ['md', 'preview', 'gfm', 'tables', 'documentation'],
    color: 'blue',
    component: lazy(() => import('../tools/markdown/MarkdownTool')),
  },
  {
    id: 'cron',
    name: 'Cron Expression Builder',
    description: 'Build five-field cron expressions visually.',
    category: 'Developer',
    icon: CalendarClock,
    keywords: ['schedule', 'interval', 'crontab', 'time'],
    color: 'purple',
    component: lazy(() => import('../tools/cron/CronTool')),
  },
  {
    id: 'qr',
    name: 'QR Code Generator',
    description: 'Create downloadable QR codes for text and URLs.',
    category: 'Generators',
    icon: QrCode,
    keywords: ['barcode', 'png', 'scan', 'qrcode'],
    color: 'teal',
    component: lazy(() => import('../tools/qr/QrTool')),
  },
  {
    id: 'case',
    name: 'Case Converter',
    description: 'Transform text into ten common case formats.',
    category: 'Converters',
    icon: CaseSensitive,
    keywords: ['camel', 'snake', 'kebab', 'pascal', 'uppercase', 'lowercase'],
    color: 'rose',
    component: lazy(() => import('../tools/case/CaseTool')),
  },
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert binary, octal, decimal, and hexadecimal exactly.',
    category: 'Converters',
    icon: Calculator,
    keywords: ['bigint', 'radix', 'integer', 'hex', 'binary'],
    color: 'green',
    component: lazy(() => import('../tools/number-base/NumberBaseTool')),
  },
  {
    id: 'contrast',
    name: 'Color Contrast Checker',
    description: 'Check foreground and background colors against WCAG.',
    category: 'Utilities',
    icon: Contrast,
    keywords: ['accessibility', 'a11y', 'aa', 'aaa', 'ratio'],
    color: 'purple',
    component: lazy(() => import('../tools/contrast/ContrastTool')),
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Inspect URL components and query parameters.',
    category: 'Developer',
    icon: ScanLine,
    keywords: ['uri', 'host', 'port', 'query', 'fragment', 'origin'],
    color: 'blue',
    component: lazy(() => import('../tools/url-parser/UrlParserTool')),
  },
  {
    id: 'image-converter',
    name: 'Image Format Converter',
    description: 'Convert PNG, JPEG and WebP locally with transparency controls.',
    category: 'Image',
    icon: Image,
    color: 'purple',
    keywords: ['jpg', 'png', 'webp', 'convert', 'file'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    producesFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    component: lazy(() =>
      import('../tools/image/ImageTool').then((module) => ({ default: module.ImageConverter })),
    ),
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image size with JPEG or WebP quality controls.',
    category: 'Image',
    icon: Minimize2,
    color: 'green',
    keywords: ['jpg', 'png', 'webp', 'compress', 'quality'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    producesFileTypes: ['image/jpeg', 'image/webp'],
    component: lazy(() =>
      import('../tools/image/ImageTool').then((module) => ({ default: module.ImageCompressor })),
    ),
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images by dimensions, percentage or common presets.',
    category: 'Image',
    icon: Scaling,
    color: 'blue',
    keywords: ['width', 'height', 'scale', 'aspect ratio'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    producesFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    component: lazy(() =>
      import('../tools/image/ImageTool').then((module) => ({ default: module.ImageResizer })),
    ),
  },
  {
    id: 'image-rotate',
    name: 'Image Rotate / Flip',
    description: 'Rotate images by quarter turns and flip either axis.',
    category: 'Image',
    icon: RotateCw,
    color: 'teal',
    keywords: ['mirror', 'orientation', '90', '180', '270'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    producesFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    component: lazy(() =>
      import('../tools/image/ImageTool').then((module) => ({ default: module.ImageRotate })),
    ),
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    description: 'Inspect image dimensions, format, file size and aspect ratio.',
    category: 'Image',
    icon: FileSearch,
    color: 'amber',
    keywords: ['mime', 'width', 'height', 'file info'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    component: lazy(() =>
      import('../tools/image/ImageTool').then((module) => ({ default: module.ImageMetadata })),
    ),
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Combine PDFs in your chosen order, entirely in your browser.',
    category: 'PDF',
    icon: FileStack,
    color: 'rose',
    keywords: ['combine', 'join', 'pages'],
    workspaceCompatible: true,
    acceptsFileTypes: ['application/pdf'],
    producesFileTypes: ['application/pdf'],
    component: lazy(() =>
      import('../tools/pdf/PdfTool').then((module) => ({ default: module.PdfMerger })),
    ),
  },
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Extract selected pages or ranges into a new PDF.',
    category: 'PDF',
    icon: Scissors,
    color: 'amber',
    keywords: ['extract', 'range', 'pages'],
    workspaceCompatible: true,
    acceptsFileTypes: ['application/pdf'],
    producesFileTypes: ['application/pdf'],
    component: lazy(() =>
      import('../tools/pdf/PdfTool').then((module) => ({ default: module.PdfSplitter })),
    ),
  },
  {
    id: 'pdf-reorder',
    name: 'PDF Page Reorder',
    description: 'Reorder or remove PDF pages with a numeric page list.',
    category: 'PDF',
    icon: ListOrdered,
    color: 'blue',
    keywords: ['move', 'sort', 'remove', 'pages'],
    workspaceCompatible: true,
    acceptsFileTypes: ['application/pdf'],
    producesFileTypes: ['application/pdf'],
    component: lazy(() =>
      import('../tools/pdf/PdfTool').then((module) => ({ default: module.PdfReorder })),
    ),
  },
  {
    id: 'images-to-pdf',
    name: 'Images → PDF',
    description: 'Turn ordered images into a PDF with page fit and margin controls.',
    category: 'PDF',
    icon: FileText,
    color: 'teal',
    keywords: ['png', 'jpeg', 'webp', 'document', 'images'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    producesFileTypes: ['application/pdf'],
    component: lazy(() =>
      import('../tools/pdf/PdfTool').then((module) => ({ default: module.ImagesToPdf })),
    ),
  },
  {
    id: 'pdf-to-images',
    name: 'PDF → Images',
    description: 'Render selected PDF pages to PNG or JPEG images locally.',
    category: 'PDF',
    icon: Image,
    color: 'purple',
    keywords: ['render', 'png', 'jpeg', 'raster', 'pages'],
    workspaceCompatible: true,
    acceptsFileTypes: ['application/pdf'],
    producesFileTypes: ['image/png', 'image/jpeg'],
    component: lazy(() => import('../tools/pdf-to-images/PdfToImages')),
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images with drag handles, aspect ratios and precise controls.',
    category: 'Image',
    icon: Crop,
    color: 'teal',
    keywords: ['crop', 'trim', 'rectangle', 'aspect', 'png', 'jpeg', 'webp'],
    workspaceCompatible: true,
    acceptsFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    producesFileTypes: ['image/png', 'image/jpeg', 'image/webp'],
    component: lazy(() => import('../tools/image-cropper/ImageCropper')),
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV Converter',
    description: 'Convert flat JSON objects and quoted CSV tables locally.',
    category: 'Converters',
    icon: FileSpreadsheet,
    color: 'green',
    keywords: ['csv', 'json', 'table', 'delimiter', 'tsv', 'spreadsheet'],
    component: lazy(() => import('../tools/json-csv/JsonCsvTool')),
  },
] satisfies Omit<ToolDefinition, 'path'>[]
export const tools: ToolDefinition[] = definitions.map((tool) => ({
  ...tool,
  path: `/tools/${tool.id}`,
}))

export function searchTools(query: string, category?: string) {
  const terms = query.toLocaleLowerCase().trim().split(/\s+/)
  return tools.filter(
    (tool) =>
      (!category || category === tool.category) &&
      terms.every((term) =>
        `${tool.name} ${tool.category} ${tool.description} ${tool.keywords.join(' ')}`
          .toLocaleLowerCase()
          .includes(term),
      ),
  )
}
